### ISSUE TITLE
Completely Disable Session & Cookie Creation

### ISSUE THREAD

**Issue by d3ep4k** [metamug/mason#30]
Disable HTTP sessions and cookies. 
https://stackoverflow.com/a/2256073/1097600

Since most servlet containers come with this feature preconfigured. They need to be disabled.
Container specific configuration is out of the scope of this issue. But within the JSP/servlet/Java Code, the issue can be addressed.

**Comment by kaisteel** [comment]
Same per the BalusC's answer the `HttpSession` won't be created whenever Request will pass via `Router` filter. Since Mason can be added as a jar in an existing web application. You'll have to explicitly disable cookies and session creation as explained in the SO answer. That is 
1. Setting `cookies` attribute in `context.xml` file
```
<Context cookies="false"/>
```
2. Setting low timeouts for Session and Cookie in `web.xml` file
```
<session-config>
    <session-timeout>1</session-timeout>
    <cookie-config>
        <max-age>0</max-age>
    </cookie-config>
</session-config>
```
